environment: production

# customization settings
title: Sam Woolf
initials: SW
description: "ramblings, code, ideas."

email: swoolf@me.com
twitter_username: 
github_username: swoolf
instagram_username: 
linkedin_url: https://www.linkedin.com/in/sam-woolf-b5914b32

# site Settings
url: "http://woolfsam.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# build settings
future: true
markdown: kramdown
exclude:
  - CNAME
  - links.jsonp
  - server.sh

# outputting
permalink: /:title/

# automatically generate a sitemap
gems:
  - jekyll-sitemap

# prose.io configuration
prose:
  siteurl: "http://woolfsam.com/"
  relativeLinks: "http://prose.github.io/starter/links.jsonp"
  media: "assets/images"
  metadata:
    posts/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "image"
        field:
          label: "image"
          element: "text"
          placeholder: "assets/image/whatever.jpg"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          placeholder: "[react, node]"
      - name: "description"
        field:
          label: "description"
          element: "textarea"
          placeholder: "about this page - to be used for SEO"
    talks/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "talk"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          label: "subtitle"
          element: "text"
          placeholder: "Deploying Application in the Cloud"
      - name: "image"
        field:
          label: "image"
          element: "text"
          placeholder: "assets/image/whatever.jpg"
      - name: "location"
        field:
          label: "location"
          element: "text"
          placeholder: "React Boston"
      - name: "locationURL"
        field:
          label: "locationURL"
          element: "text"
          placeholder: "http://www.meetup.com/ReactJS-Boston/events/226726417/"
      - name: "gitHub"
        field:
          label: "related gitHub repo"
          element: "text"
          placeholder: "https://github.com/kauffecup/react-d3-examples"
      - name: "blog"
        field:
          label: "related blog title"
          element: "text"
          placeholder: "react-d3-love"
      - name: "slidr"
        field:
          label: "slidr"
          element: "text"
          placeholder: "https://slidr.io/kauffecup/react-d3-3"
      - name: "dataCardKey"
        field:
          label: "dataCardKey"
          element: "text"
          placeholder: "c7eb2be95ffc4d709de201b870895b9b"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          placeholder: "[react, node]"
      - name: "abstract"
        field:
          label: "abstract"
          element: "textarea"
          placeholder: "c7eb2be95ffc4d709de201b870895b9b"
